version: '3.7'

services:
  db-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: educator
      POSTGRES_PASSWORD: postgreSS!
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"

volumes:
      postgres: